# ============================================================
# SOURCE 4: CONDITIONAL IDENTIFIABILITY FOR H(theta)
# ============================================================
#
# This module studies the conditional problem in which the
# smooth vector f* is fixed and the parameter theta changes.
#
# Two cases are considered:
#
#   A. f* generates only a proper subspace of R^2.
#   B. f* generates all of R^2.
#
# The purpose is to show that identification of theta depends on
# how H(theta) acts on the subspace generated by f*.
# ============================================================


run_conditional_H_theta <- function(common) {

  x1 <- common$x1
  x2 <- common$x2


  # ----------------------------------------------------------
  # Parametrized constraint matrix
  # ----------------------------------------------------------

  H_theta <- function(theta) {

    matrix(
      c(
        1, theta,
        0, 1
      ),
      nrow = 2,
      byrow = TRUE
    )
  }


  theta1 <- 0.5
  theta2 <- 1.5


  # ==========================================================
  # CASE A: f* GENERATES A PROPER SUBSPACE OF R^2
  # ==========================================================
  #
  # Only the first latent coordinate varies. Therefore the
  # observed latent vectors span the direction (1,0)'.

  z1 <- (
    sin(pi * x1) +
      0.30 * cos(pi * x2) +
      0.10 * x1 * x2
  )


  z1 <- (
    z1 -
      mean(z1)
  )


  Fstar_restricted <- cbind(
    z1,
    rep(0, length(z1))
  )


  rank_Fstar_restricted <- matrix_rank(
    Fstar_restricted
  )


  eta_theta1_restricted <- (
    Fstar_restricted %*%
      t(
        H_theta(theta1)
      )
  )


  eta_theta2_restricted <- (
    Fstar_restricted %*%
      t(
        H_theta(theta2)
      )
  )


  difference_theta_restricted <- max_abs_diff(
    eta_theta1_restricted,
    eta_theta2_restricted
  )


  # ==========================================================
  # CASE B: f* GENERATES R^2
  # ==========================================================
  #
  # Two linearly independent latent coordinates are used.
  # Both depend on the full bivariate covariate vector.

  z1_full <- (
    sin(pi * x1) +
      0.25 * cos(pi * x2) +
      0.08 * x1 * x2
  )


  z2_full <- (
    cos(2 * pi * x1) -
      0.20 * sin(pi * x2) +
      0.12 * x1 * x2
  )


  Fstar_full <- cbind(
    z1_full,
    z2_full
  )


  Fstar_full <- center_columns(
    Fstar_full
  )


  rank_Fstar_full <- matrix_rank(
    Fstar_full
  )


  eta_theta1_full <- (
    Fstar_full %*%
      t(
        H_theta(theta1)
      )
  )


  eta_theta2_full <- (
    Fstar_full %*%
      t(
        H_theta(theta2)
      )
  )


  difference_theta_full <- max_abs_diff(
    eta_theta1_full,
    eta_theta2_full
  )


  # ----------------------------------------------------------
  # Summary
  # ----------------------------------------------------------

  conditional_results <- data.frame(
    case = c(
      "Proper subspace",
      "Full span"
    ),
    rank_Fstar = c(
      rank_Fstar_restricted,
      rank_Fstar_full
    ),
    predictor_difference = c(
      difference_theta_restricted,
      difference_theta_full
    )
  )


  # The observed covariates themselves must remain genuinely
  # two-dimensional.
  X_covariates <- cbind(
    x1,
    x2
  )


  rank_X_covariates <- matrix_rank(
    X_covariates
  )


  # Numerical verification.
  stopifnot(
    rank_X_covariates == 2
  )

  stopifnot(
    rank_Fstar_restricted == 1
  )

  stopifnot(
    rank_Fstar_full == 2
  )

  stopifnot(
    difference_theta_restricted < 1e-10
  )

  stopifnot(
    difference_theta_full > 1e-8
  )


  list(
    H_theta = H_theta,
    theta1 = theta1,
    theta2 = theta2,
    Fstar_restricted = Fstar_restricted,
    rank_Fstar_restricted = rank_Fstar_restricted,
    eta_theta1_restricted = eta_theta1_restricted,
    eta_theta2_restricted = eta_theta2_restricted,
    difference_theta_restricted = difference_theta_restricted,
    Fstar_full = Fstar_full,
    rank_Fstar_full = rank_Fstar_full,
    eta_theta1_full = eta_theta1_full,
    eta_theta2_full = eta_theta2_full,
    difference_theta_full = difference_theta_full,
    conditional_results = conditional_results,
    rank_X_covariates = rank_X_covariates
  )
}
